### ISSUE TITLE
Selecting pharmacy did not show up.

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#100]
Akira has posted an issue in Discord

Selecting pharmacy did not show up.

**Comment by Grrom** [comment]
this is the appointment where this occured,

https://practitioner-portal.web.app/appointments/64f467ae-0dcc-4e04-aab0-0e2c91101488

notification seems to have been created
![image](https://github.com/umed-jp/umed/assets/62323308/9721060c-0851-4467-b7ba-1e35a06ab92e)


the empty chosen pharmacy document was generated so it's a bit weird that the chosen pharmacy component is not showing up in the homescreen

**Comment by Grrom** [comment]
the cloud function ran during the timestamp where the appointment is ended so it looks like the the notification function must have been sent
![image](https://github.com/umed-jp/umed/assets/62323308/dac933d4-0e33-44bd-ade5-ec6348fbac1f)

**Comment by Grrom** [comment]
the notification handler also seems to have executed successfully
![image](https://github.com/umed-jp/umed/assets/62323308/8fc9339d-ecd8-4764-a938-a696b1d1d2e2)

**Comment by Grrom** [comment]
this is where the encounter was ended
https://console.cloud.google.com/logs/query;cursorTimestamp=2024-05-28T00:11:19.749391Z;endTime=2024-05-28T00:13:20.790Z;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22run-kitsune-prod-asia-northeast1%22%0Aresource.labels.location%20%3D%20%22asia-northeast1%22%0A%20severity%3E%3DDEFAULT%0Atimestamp%3D%222024-05-28T00:11:19.491072Z%22%0AinsertId%3D%2266552127000d26ed25bb75fb%22;startTime=2024-05-28T00:09:20.790Z?project=kitsune-prod
![image](https://github.com/umed-jp/umed/assets/62323308/8ef65f6f-12bd-4714-b718-3ddadf7721b9)

**Comment by Grrom** [comment]
the pubsub message that was send when this encounter was finished

https://console.cloud.google.com/logs/query;cursorTimestamp=2024-05-28T00:11:21.621757Z;endTime=2024-05-28T00:13:20.790Z;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22run-kitsune-prod-asia-northeast1%22%0Aresource.labels.location%20%3D%20%22asia-northeast1%22%0A%20severity%3E%3DDEFAULT%0Atimestamp%3D%222024-05-28T00:11:21.620599Z%22%0AinsertId%3D%2266552129000977539daad407%22;startTime=2024-05-28T00:09:20.790Z?project=kitsune-prod
![image](https://github.com/umed-jp/umed/assets/62323308/25a989b9-72c4-4a38-9dfb-24b234ad886b)

**Comment by Grrom** [comment]
looking at the logs and communication between our services everything seems to have worked as expected.

**Comment by Grrom** [comment]
one thing I find suspicious is that the notification data that was added has `is_read` set to `false`
so this might be an issue in the frontend with displaying the notification (or maybe the patient didn't bother checking the notif) not sure yet

![image](https://github.com/umed-jp/umed/assets/62323308/eb13dd66-c5d1-4c62-bd1b-fe7a987c231b)

**Comment by Grrom** [comment]
this fix, should also cover this since the notification can redirect the patient

still, it's weird that the component didn't show up in the home page.
unless it happens again, I think we can close this?

<img width="970" alt="image" src="https://github.com/umed-jp/umed/assets/62323308/0b128bb2-effd-48e8-9cde-8c4403c74478">

**Comment by castilloglenn** [comment]
This can be closed by June 12 if not occurred again.
