### ISSUE TITLE
Found an issue for combining wakin and scheduled

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#102]
Akira has posted an issue in Discord

Found an issue for combining wakin and scheduled

**Comment by castilloglenn** [comment]
![image](https://github.com/umed-jp/umed/assets/55197203/c04dbb07-28d1-4814-bd9a-cef7be3abbcd)
No slot available but it's available

**Comment by castilloglenn** [comment]
Expected behavior: The earliest timeslot for the next day shall be shown, instead of showing the one in the snippet

**Comment by castilloglenn** [comment]
This is done: https://github.com/umed-jp/kitsune-backend/pull/496

**Comment by castilloglenn** [comment]
Will close
CC: @rafael-parayno
