### ISSUE TITLE
when there the appointment call is not picked up, you get the notification and clicking on it goes to LINE

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#103]
Akira has posted an issue in Discord

<@&1219098225458282546> when there the appointment call is not picked up, you get the notificaiton and clicking on it goes to LINE

**Comment by castilloglenn** [comment]
From Akira: but I thnk it should go to appointment detail page for the pick up

**Comment by Grrom** [comment]
this is kinda weird,
is this the notification message that showed up?
@akirakakar 
![image](https://github.com/umed-jp/umed/assets/62323308/bbf35ee7-3edf-4db5-a16f-299b4e8490ed)

since this one doesn't have a path, not sure why it redirected to main,
I'm investigating now

**Comment by Grrom** [comment]
this PR fixes the issue
- https://github.com/umed-jp/notification-publisher/pull/61
