### ISSUE TITLE
🚀 :  unstable selection of patient preferred medication

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#108]
Raf23 has posted an issue in Discord

the selecting the patient preferred is not stable on the main,

**Comment by castilloglenn** [comment]
https://discord.com/channels/1161110836635508778/1176408561379725372/1246052596989427743

**Comment by akirakakar** [comment]
https://github.com/umed-jp/umed/assets/38812367/23ab9e26-5483-4cdf-9345-b5c551c2b157

**Comment by tammytamayao** [comment]
fix: https://github.com/umed-jp/practitioner-frontend-ts/pull/616
