### ISSUE TITLE
Payment is not completed

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#11]
**Describe the bug**
Payment is not completed for one particular user.

PatientID: 105344f2-669e-4345-a8fa-266eb4ea0d3b.
EncounterID: 07ca7760-c9fc-40b1-b5d6-70895ee87569

**Expected behavior**
Charge this patient correctly.

**Screenshots**
<img width="814" alt="Screenshot 2024-03-06 at 18 51 52" src="https://github.com/umed-jp/umed/assets/38812367/27d31fbf-0767-46ca-9ae6-2a86f61d428b">

**Comment by castilloglenn** [comment]
## Current state before charging:

Account resource:
<img width="464" alt="image" src="https://github.com/umed-jp/umed/assets/55197203/6800ab6e-f15d-45bb-8b9d-5f01e00cfa4e">

Stripe last payment record:
<img width="1024" alt="image" src="https://github.com/umed-jp/umed/assets/55197203/578b33b8-8885-4599-b8d1-f837c7a22685">

**Comment by castilloglenn** [comment]
## After charging

Account resource:
<img width="450" alt="image" src="https://github.com/umed-jp/umed/assets/55197203/6e730e06-e906-4d28-8eab-54d11a4b868a">

Stripe payment history:
<img width="1027" alt="image" src="https://github.com/umed-jp/umed/assets/55197203/c9397f23-3cf2-4b56-b466-f57f7f5b2db3">

**Comment by castilloglenn** [comment]
<img width="550" alt="image" src="https://github.com/umed-jp/umed/assets/55197203/8b95ce5e-bddd-4947-9643-e5dae8c15c6d">

done charging @akirakakar -san 🙇🏽
