### ISSUE TITLE
Walk-In is opend again although walk-in is supposed to be closed by the doctor

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#115]
Akira has posted an issue in Discord

Walk-In is opend again although walk-in is supposed to be closed by the doctor

**Comment by akirakakar** [comment]
@tammytamayao, please get help from @Grrom

**Comment by Grrom** [comment]
PR
- https://github.com/umed-jp/KitsuneWebsocket/pull/7

more info on the PR description
