### ISSUE TITLE
🚀 : patient can book appointment for Jun-8 although in the setting it says end date is June-7

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#116]
Akira has posted an issue in Discord

<@&1219098225458282546> 
Patient can book  the apointment for Jun-8 although in the setting it says that the end date is June-7

**Comment by akirakakar** [comment]
Please take a look if this is actually fixed or not?

**Comment by tammytamayao** [comment]
https://github.com/umed-jp/umed/issues/124
