### ISSUE TITLE
We had two notifications when the appointment was booked

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#120]
**Describe the bug**
When a patient books an appointment, he gets two appointments

**To Reproduce**
1. Book scheduled appointment

**Expected behavior**

Only one notification

**Screenshots**
![IMG_0892](https://github.com/umed-jp/umed/assets/38812367/b8b0b619-85eb-4add-8c3e-6c14332b52ca)

**Comment by Grrom** [comment]
when this happens, we might want to check FHIR in gcp first to see if there are multiple topics like this
<img width="1263" alt="image" src="https://github.com/umed-jp/umed/assets/62323308/62f89e9e-ab20-4607-bcf6-c9c1bda5ac95">


the quick fix is to remove the duplicate, but the real fix should be to prevent this from happening in the first place.
issue is likely on infra (I think)

**Comment by akirakakar** [comment]
The root cause is not fixed.  Opening another issue to fix the infra.
Opening new issue, https://github.com/umed-jp/umed/issues/121
