### ISSUE TITLE
🚀 Merged to dev: unexpected access to cancelled appointment details page via notifications

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#14]
# Describe the bug
we don't have a UI now for cancelled appointment, At first it wasn't a problem because we are preventing the user from opening the appointment detail page from the appointment history if it was cancelled but now that we have the notifications hub, the patient can visit the appointment detail page directly

# To Reproduce
```
trigger any notification that redirects to the appointment details page in patient-app
cancel the appointment
open patient app and click on the appointment
```

# Expected behavior
The appointment details page should clearly show that that specific appointment has been cancelled

# Screenshots
<video src="https://github.com/umed-jp/umed/assets/62323308/cc8b7928-ed24-4cbe-96a8-da6c24cd033c" />

**Comment by fauortiz** [comment]
Scope for this issue is narrowed down to preventing the patient from accessing the appointment detail page from the notifications hub.

Adding the UI for cancelled appointment in appointment details page can be scoped out into a full user story.

**Comment by fauortiz** [comment]
issue is resolved by setting the hasAction flag to false for cancelled appointments when generating notifications.
this code can be removed once the UI for cancelled appointments is implemented. CC @rafael-parayno 

Edit: this did not resolve the issue, but another issue, where the appointment cancelled notification allowed you to enter the appointment detail page. The actual fix is below.

<img width="905" alt="Screenshot 2024-04-06 at 6 29 23 PM" src="https://github.com/umed-jp/umed/assets/67045972/6552a197-7bcc-4c8a-8f53-6cee453e4661">

**Comment by fauortiz** [comment]
- https://github.com/umed-jp/kitsune-frontend/pull/976 disables the redirect for cancelled encounters.

![image](https://github.com/umed-jp/umed/assets/67045972/2d235aa3-59c3-4878-aba4-64348026d294)
