### ISSUE TITLE
🎉  Done: enable_remove_registration is false

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#17]
**Describe the bug**
enable_remove_registration is set to false even after we have release the feature 

**Expected behavior**
update  enable_remove_registration to true so that it does not happen again

**Screenshots**
<img width="1089" alt="Screenshot 2024-03-07 at 11 31 25" src="https://github.com/umed-jp/umed/assets/38812367/acbbdfd8-051f-4f29-ac1c-460d93f182fa">

**Additional context**
I turned it on for now but should be fixed in the repo.

**Comment by Grrom** [comment]
I have a PR that removes this

- https://github.com/umed-jp/kitsune-remote-config/pull/28

but we still need to deploy the linked PR to appstore before we promote the remote-config to prod
- https://github.com/umed-jp/kitsune-frontend/pull/961

**Comment by castilloglenn** [comment]
The issue should be resolved once the PR's of @Grrom is merged and released.

**Comment by Grrom** [comment]
- I think this shouldn't be marked as done until [e26ff9ef48d2008215352b73b663252a6a84ae1d](https://github.com/umed-jp/kitsune-frontend/commit/e26ff9ef48d2008215352b73b663252a6a84ae1d) is released to appstore

**Comment by fauortiz** [comment]
released in 0.12.6
