### ISSUE TITLE
end encounter doesn't update the backend

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#22]
Raf23 has posted an issue in Discord

i tried clicking the end encounter on appointment details it does process it updates the status on the appointment detail but it doesnt update on the backend and the list

**Comment by castilloglenn** [comment]
for this one this is a correlated repercussion of the root cause of this other bug:
- https://github.com/umed-jp/umed/issues/15

**Comment by castilloglenn** [comment]
The issue is with the syncing of statuses in the frontend.

**Comment by castilloglenn** [comment]
These two are related
- https://github.com/umed-jp/umed/issues/23

**Comment by castilloglenn** [comment]
fix merged
