### ISSUE TITLE
the encounter is already finished but still on this component

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#23]
Raf23 has posted an issue in Discord

the encounter is already finished but still on this component

**Comment by castilloglenn** [comment]
for this one this is a correlated repercussion of the root cause of this other bug:
- https://github.com/umed-jp/umed/issues/15

**Comment by castilloglenn** [comment]
The issue is with the syncing of statuses in the frontend.

**Comment by castilloglenn** [comment]
fix merged
