### ISSUE TITLE
Unsend is not working

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#26]
**Describe the bug**

SBO sent the notificaiton by mistake and cannot be cancelled

**Expected behavior**

Notification is unsend

**Screenshots**
<img width="575" alt="Screenshot 2024-03-08 at 19 06 52" src="https://github.com/umed-jp/umed/assets/38812367/3d48d4e5-902e-40e9-a0cb-4e19e7d92d50">

**Comment by akirakakar** [comment]
Since we wanted to unsend before patient sees the message, we have deleted the notification directly from the firestore notificaiton collection.

**Comment by rafael-parayno** [comment]
it does work, we just need to release it some other parts of it, which we already release.

**Comment by rafael-parayno** [comment]
which is these two,

https://github.com/umed-jp/notification-publisher/pull/27 
https://github.com/umed-jp/kitsune-firestore/pull/30/files

**Comment by castilloglenn** [comment]
fixed by @rafael-parayno
