### ISSUE TITLE
🎉 Done: API Endpoint for medication_requests is using wrong standard

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#29]
**Describe the issue**
Currently, we have
```medication_requests/encounter/{encounter['id']}```

but we want 
```medication_requests?encounter={encounter['id']}```

**Comment by castilloglenn** [comment]
This change is for the backend endpoint, but also requires refactoring of the two frontend usage.

**Comment by fauortiz** [comment]
AB#3881

**Comment by rafael-parayno** [comment]
AB#4128

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/kitsune-frontend/pull/1005

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/kitsune-backend/pull/476
