### ISSUE TITLE
🎉 Done: notification badge doesn't show when user is not in queue route

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#31]
Miwa has posted an issue in Discord

About the notification issue,  when the practitioner opens the tab, except for queuing, notification badge doesn't be shown.

----
Solution PR:
https://github.com/umed-jp/practitioner-frontend-ts/pull/444

**Comment by castilloglenn** [comment]
https://discord.com/channels/1161110836635508778/1176408561379725372/1217386391022075916

**Comment by castilloglenn** [comment]
https://github.com/umed-jp/umed/assets/55197203/74a51ad7-2a9d-4d0d-a05d-7daf9a0d4c48

**Comment by tammytamayao** [comment]
PR: https://github.com/umed-jp/practitioner-frontend-ts/pull/444
