### ISSUE TITLE
prescription is doubled

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#32]
Miwa has posted an issue in Discord

There is a bug that when I check the appointment I just look again from fulfilled status, two of the same drugs are saved.

**Comment by castilloglenn** [comment]
solution discussion: https://discord.com/channels/1161110836635508778/1217743656753172480

**Comment by castilloglenn** [comment]
This issue spans on both the frontend and backend, so it will be linked to multiple PR's:
- https://github.com/umed-jp/kitsune-backend/pull/439
- https://github.com/umed-jp/practitioner-frontend-ts/pull/432
- https://github.com/umed-jp/kitsune-backend/pull/440

Tickets:
- https://dev.azure.com/UMedInc/Engineering/_workitems/edit/3839
- https://dev.azure.com/UMedInc/Engineering/_workitems/edit/3842
- https://dev.azure.com/UMedInc/Engineering/_workitems/edit/3840
- https://dev.azure.com/UMedInc/Engineering/_workitems/edit/3841
- https://dev.azure.com/UMedInc/Engineering/_workitems/edit/3844

**Comment by castilloglenn** [comment]
This PR also helps in mitigating this issue and others:
- https://github.com/umed-jp/practitioner-frontend-ts/pull/433

**Comment by castilloglenn** [comment]
I guess this one's resolves the root cause of this issue:
- https://github.com/umed-jp/practitioner-frontend-ts/pull/436

**Comment by tammytamayao** [comment]
@Grrom -san's PR fixed this issue:
PR: https://github.com/umed-jp/practitioner-frontend-ts/pull/436
