### ISSUE TITLE
encounter gets finished unexpectedly

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#33]
Miwa has posted an issue in Discord

It seems like the bug "end encounter" button disappeared, unrelated to the time.  
I do the ordinary operation but the status automatically changed FINISHED.

**Comment by castilloglenn** [comment]
We need to gather more information about this bug, how to recreate it.

**Comment by tammytamayao** [comment]
This is not already reproducible based on my meeting with @MiwaNishikawa -san (March 21, 2024)
