### ISSUE TITLE
end session button disappears after 10 mins

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#35]
Miwa has posted an issue in Discord

After 10 minutes from the start of the consultation, the end-of-consultation button disappears.

**Comment by castilloglenn** [comment]
https://discord.com/channels/1161110836635508778/1176408561379725372/1217386665388281896

**Comment by castilloglenn** [comment]
![image](https://github.com/umed-jp/umed/assets/55197203/ca9ba9f5-8d3e-42ff-8b61-2a0bf6dbb928)

**Comment by tammytamayao** [comment]
[Memo](https://discord.com/channels/1161110836635508778/1217386665388281896/1220188868444160090) notes
Meeting with @MiwaNishikawa -san 

It cannot already be reproduced.
