### ISSUE TITLE
For the staff account , if we clicked on in-progress(autoamtically turns in-progress), it pops a dialog to finish the appointment.

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#37]
Akira has posted an issue in Discord

For the staff account , if we clicked on in-progress(autoamtically turns in-progress), it pops a dialog to finish the appointment.

**Comment by castilloglenn** [comment]
Fix by @Grrom:
- https://github.com/umed-jp/practitioner-frontend-ts/pull/421

**Comment by castilloglenn** [comment]
same issue as this one

- https://github.com/umed-jp/umed/issues/36
