### ISSUE TITLE
Cancel Status is not showing up

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#38]
Akira has posted an issue in Discord

Cancel Status is not showing up

**Comment by akirakakar** [comment]
appointmentId: 7e10c516-6ad9-41ed-bdaf-af7d5ea198b3
status: cancelled

encounterId: 05ce0998-8832-4a99-b0d9-728f5800ec6e
status: in-progress

**Comment by akirakakar** [comment]
![Screenshot 2024-03-16 at 9 17 21](https://github.com/umed-jp/umed/assets/38812367/1a5b57fb-be53-4c15-a548-e20bbe61ddcb)

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/practitioner-frontend-ts/pull/429

**Comment by castilloglenn** [comment]
the fix is merged.
