### ISSUE TITLE
Encounter turns "finished" automatically

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#39]
Akira has posted an issue in Discord

Encounter turns "finished" automatically

**Comment by castilloglenn** [comment]
I think we need more details about this

**Comment by tammytamayao** [comment]
Duplicated Issue:
- https://github.com/umed-jp/umed/issues/33

**Comment by tammytamayao** [comment]
This is not already reproducible based on my meeting with @MiwaNishikawa  -san (March 21, 2024)
