### ISSUE TITLE
🎉 Done:we are fetching too many medications in AppointmentDetailPage

### ISSUE THREAD

**Issue by castilloglenn** [umed-jp/umed#41]
![image](https://github.com/umed-jp/umed/assets/55197203/99be8560-de40-4c04-aee9-a09776c9d305)

**Comment by castilloglenn** [comment]
This raises some rate limit issues for the users

**Comment by castilloglenn** [comment]
Solution here is to lazy load the medication requests and only fetch if the component is visible.

**Comment by akirakakar** [comment]
We are fetching the medications by patient.

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/practitioner-frontend-ts/pull/535
