### ISSUE TITLE
🎉 Done: choose pharmacy card is not displaying

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#44]
Akira has posted an issue in Discord

A patient had a issue that the instruction card was removed

**Comment by akirakakar** [comment]
1. Thoroughly check all scenarios involving the instruction card
2. Add log if required

**Comment by fauortiz** [comment]
AB#3882

details regarding the issue:
the patient walks in. after queueing, the join call instruction screen does not render. instead, the user is sent to the home page.

Video from Akira:

https://github.com/umed-jp/umed/assets/67045972/d8a8f56b-3ae8-4d40-bd8e-5d18f65c4592

**Comment by fauortiz** [comment]
**issue found:**
The "isDeleted" field for the chosen_pharmacy documents in Firestore is not initialized, making the database filter always empty.

![image](https://github.com/umed-jp/umed/assets/67045972/31c29212-dd39-4de0-8526-e545b5ada839)

I'll set the default value for isDeleted to false.

**Comment by fauortiz** [comment]
deployed to prod.
