### ISSUE TITLE
duplicated medications

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#47]
Akira has posted an issue in Discord

Duplicates were created (similar medications were added according to <@1092693321966698526>  as this might be a bug)
https://practitioner-portal.web.app/encounters/ff0edefc-da50-4928-8e66-112b2dc223b5/medical-information
<@865828035340795915>

**Comment by akirakakar** [comment]
Next action item:
* Add a log so that we can catch it later.

**Comment by fauortiz** [comment]
similar to
- https://github.com/umed-jp/umed/issues/32
