### ISSUE TITLE
🚀  : send by mail "preparing" status not filtering correctly

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#57]
Akira has posted an issue in Discord

item is filtered out although status is not ready state.

https://practitioner-portal.web.app/encounters/2a8b7227-07f0-466c-b2cd-e3bc57c57959/medical-information

**Comment by fauortiz** [comment]
![image](https://github.com/umed-jp/umed/assets/67045972/faa4cddb-5d14-4c7b-9d0e-4a1c608f4f19)
![image](https://github.com/umed-jp/umed/assets/67045972/7f067ef5-71c8-4262-bc69-0be712b2deff)

**Comment by rafael-parayno** [comment]
@akirakakar -san more details

**Comment by tammytamayao** [comment]
fix: https://github.com/umed-jp/practitioner-frontend-ts/pull/620
