### ISSUE TITLE
Appointment is not showing up in the order

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#58]
Akira has posted an issue in Discord

<@520447604266631172> 
https://practitioner-portal.web.app/appointments/0932c586-5fec-49df-9076-264fe9b26a76

This appointment is not showing up in the order

**Comment by fauortiz** [comment]
Added details/actions:
Akira — Today at 5:08 PM
For quick resolution, I will change the status of encounter from finished -> in-progress -> finished
I asked sbo and they said that they did not open Notion page.

Findings:
- Encounter ID: a59c252a-52e2-40b5-afac-11d140d5daad (in prod)
- There were no error logs on the backend.
- Notion was not involved (so it's not related to the previous issue, and concurrency is less likely to be the problem)
- The workaround (reverting to in-progress and back) fixed it. (which means the firestore data is now correct)

I can't figure out what it could be, outside of connectivity issues or similar
