### ISSUE TITLE
🎉Done: Updating the credit card on kitsune-frontend not working

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#61]
Akira has posted an issue in Discord

<@520447604266631172> 

Updating the credit card on kitsune-frontend is not working.
This have confirmed that this is happening in the lastest main and the prod (apple store)

**Comment by fauortiz** [comment]
To reproduce:
go to credit card component and tap 'add credit card'. Nothing should happen. Error log below.

flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Null check operator used on a null value
flutter:
0      PageRedirect.page
route_middleware.dart:199
1      GetMaterialApp.generator
get_material_app.dart:340
2      _WidgetsAppState._onGenerateRoute
app.dart:1439
3      NavigatorState._routeNamed
navigator.dart:4138
4      NavigatorState.pushNamed
navigator.dart:4197
5      GetNavigation.toNamed
extension_navigation.dart:592
6      PaymentMethodPage.build.<anonymous closure>.<anonymous closure>.<anonymous closure>
payment_method_page.dart:164
7      _InkResponseState.handleTap
ink_well.dart:1096
8      GestureRecognizer.invokeCallback
recognizer.dart:253
9      TapGestureRecognizer.handleTapUp
tap.dart:627
10  <…>
flutter: ----------------------------------------------------

**Comment by fauortiz** [comment]
the issue was that the old component for adding credit cards was removed while developing the delayed registration feature. the fix makes a new component to replace it.

Discord thread:
https://discord.com/channels/1161110836635508778/1228212779417206844

**Comment by akirakakar** [comment]
This is the commit: https://github.com/umed-jp/kitsune-frontend/pull/982

**Comment by akirakakar** [comment]
This is merged and promoted to the Apple store by 0.12.7.
