### ISSUE TITLE
In review: One of the patiets was stuck at the chief of complaint

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#63]
Akira has posted an issue in Discord

<@906813918142402592> 
One of the patiets was stuck at the chief of complaint

**Comment by suvratgarg** [comment]
have not been able to replicate yet

**Comment by rafael-parayno** [comment]
this can be fixed via retry mechanism

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/kitsune-frontend/pull/998
