### ISSUE TITLE
🎉Done: We have unreasonably many notificaitoin to slack. Not sure if this is only to the slack or also to the patient

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#65]
Akira has posted an issue in Discord

We have unreasonably many notificaitoin to slack. Not sure if this is only to the slack or also to the patient

**Comment by rafael-parayno** [comment]
done fixing,

![image](https://github.com/umed-jp/umed/assets/52073048/0d35df1c-16f1-45c5-8845-3ce59eb4aac0)

the problem is it has multiple pubsub attach to the fhir

fix is to remove the duplicate.
