### ISSUE TITLE
🎉 Done: Pre-questionnaire has a medicine that was not prescribed previously and he mentioned that he hasn't chosen one

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#79]
Akira has posted an issue in Discord

<@&1219098225458282546> 
https://practitioner-portal.web.app/appointments/033f1735-b5c4-426f-906d-f5d60f61bf17
Pre-questionnaire has a medicine that was not prescribed previously and he mentioned that he hasn't chosen one

**Comment by rafael-parayno** [comment]
https://practitioner-portal.web.app/appointments/033f1735-b5c4-426f-906d-f5d60f61bf17

**Comment by rafael-parayno** [comment]
Duplicate issue

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/umed/issues/73
