### ISSUE TITLE
🎉 Done: update patient medicine resource rules

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#85]
Akira has posted an issue in Discord

match /patient_medicine_request/{patientMedicineRequestId} {
      allow write: if isSignedIn(request) && isOneOfRoles(request, 'Patient');
      allow read: if isSignedIn(request) && (isOneOfRoles(request, 'Practitioner') || isOneOfRoles(request, 'Patient')) || isOneOfRoles(request, 'Staff');

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/kitsune-firestore/pull/38
