### ISSUE TITLE
two notifications are received in slack

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#86]
Raf23 has posted an issue in Discord

two notifications

**Comment by Grrom** [comment]
<img width="772" alt="image" src="https://github.com/umed-jp/umed/assets/62323308/6642d6ec-2382-46f8-a846-6e4bc4bff3cd">

**Comment by Grrom** [comment]
PR opened
- https://github.com/umed-jp/notification-publisher/pull/56
