### ISSUE TITLE
🎉 Done: error on getting of patient

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#88]
Raf23 has posted an issue in Discord

error on getting of patient

**Comment by rafael-parayno** [comment]
E   entry -> 23 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 24 -> resource -> name -> 2 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 24 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 26 -> resource -> name -> 2 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 26 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 29 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 30 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 32 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 33 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)
E   entry -> 40 -> resource -> name -> 3 -> family
E     string does not match regex "[ \r\n\t\S]+" (type=value_error.str.regex; pattern=[ \r\n\t\S]+)

it not allowed to have only string of white space on the family

**Comment by rafael-parayno** [comment]
https://github.com/umed-jp/kitsune-backend/pull/482
