### ISSUE TITLE
Had duplicate medication requests

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#93]
Akira has posted an issue in Discord

<@&1219098225458282546> Had duplicate medication requests.
https://practitioner-portal.web.app/appointments/6846ed10-8006-43c7-a041-79d3896d7bc6

**Comment by Grrom** [comment]
looks like multiple requests were sent almost at the same time
![image](https://github.com/umed-jp/umed/assets/62323308/6843abc7-7f94-4dcf-85d6-3020211af70f)

**Comment by Grrom** [comment]
I can't reproduce right now

**Comment by Grrom** [comment]
- https://github.com/umed-jp/kitsune-backend/pull/481
