### ISSUE TITLE
Can you investigate if NPS is working correctky with the survey link as well?This is because we don't see new NPS and suvey since May 7th

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#98]
Akira has posted an issue in Discord

<@&1219098225458282546> Can you investigate if NPS is working correctky with the survey link as well?
This is because we don't see new NPS and suvey since May 7th

**Comment by Grrom** [comment]
cloud function to send the notifications is still functioning as of today
![image](https://github.com/umed-jp/umed/assets/62323308/c122eb78-4111-4773-ba66-769008ab8203)

**Comment by Grrom** [comment]
![image](https://github.com/umed-jp/umed/assets/62323308/057a21be-bdf6-4776-ad50-8e8119909370)
this is a notification from the latest pharmacy choice in prod right now,

sent may 25 2024

**Comment by Grrom** [comment]
It's also still showing up on dev

![IMG_9D12CA83B3A0-1](https://github.com/umed-jp/umed/assets/62323308/f90360e6-1c55-4208-aaf3-110aa06b5495)

**Comment by Grrom** [comment]
<img width="1012" alt="image" src="https://github.com/umed-jp/umed/assets/62323308/62d5c1ca-b53a-4425-b54f-ea1a009cae28">

**Comment by castilloglenn** [comment]
This one is already working, will close 🙇🏽
