### ISSUE TITLE
Prefered medication is not showing up in the pre-questionnaire

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#99]
Akira has posted an issue in Discord

<@567680071628881921> <@&1219098225458282546> 
Prefered medication is not showing up in the pre-questionnaire

**Comment by Grrom** [comment]
- https://github.com/umed-jp/practitioner-frontend-ts/pull/556

**Comment by castilloglenn** [comment]
Not reported again, closing 🙇🏽
